### ISSUE TITLE
[BUG]: HealthMetrics error while gradle sync if using buildSpeed

### ISSUE THREAD

**Issue by Blighting** [VKCOM/vkid-android-sdk#40]
### Опишите баг

При синке проекта возникает ошибка 
```
Could not create task ':healthMetricsBuildSpeed02eea39fb68e5880d8fa6ad786665062b424b941a8bfad01ea20ab3b404b4c37Iteration1'.
A dependency must not be empty
```
Более подробные логи
```Exception is:
org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':healthMetricsBuildSpeed02eea39fb68e5880d8fa6ad786665062b424b941a8bfad01ea20ab3b404b4c37Iteration1'.
	/* non vkid logs */
	at com.vk.id.health.metrics.buildspeed.VKIDBuildSpeedMetric.<init>(VKIDBuildSpeedMetric.kt:45)
	at com.vk.id.health.metrics.buildspeed.VKIDBuildSpeedMetric$Builder.build$metrics(VKIDBuildSpeedMetric.kt:167)
	at com.vk.id.health.metrics.buildspeed.VKIDBuildSpeedMetricKt.buildSpeed(VKIDBuildSpeedMetric.kt:29)
        /* non vkid logs */
       Caused by: org.gradle.api.InvalidUserDataException: A dependency must not be empty
	at org.gradle.api.internal.tasks.DefaultTaskDependency.addValue(DefaultTaskDependency.java:200)
	at org.gradle.api.internal.tasks.DefaultTaskDependency.add(DefaultTaskDependency.java:193)
```
На данный момент плагин конфигируется так:
```kotlin
import com.vk.id.health.metrics.buildspeed.buildSpeed
import com.vk.id.health.metrics.codecoverage.codeCoverage
import com.vk.id.health.metrics.gitlab.gitlab
import com.vk.id.health.metrics.storage.firestore
import java.util.Properties

healthMetrics {
    val localProperties by lazy {
        Properties().apply { load(rootProject.file("bot.properties").inputStream()) }
    }
    gitlab(
        host = { localProperties.getProperty("healthmetrics.gitlab.host") },
        token = { localProperties.getProperty("healthmetrics.gitlab.token") },
        projectId = { localProperties.getProperty("healthmetrics.gitlab.projectId") }
    )
    firestore(rootProject.file("build-logic/metrics/service-credentials.json"))
    codeCoverage {
        title = "Code coverage"
        targetProject = rootProject
    }
    buildSpeed {
        title = "Build speed of :assembleDebug"
        measuredTaskPaths = setOf(":assembleDebug")
        iterations = 3
        warmUps = 2
        cleanAfterEachBuild = true
    }
}
```
```kotlin
plugins {
    alias(libs.plugins.health)
}
```

### Вопроизведение

1. Создать чистый проект в студии без активити
2. Добавить плагин 
build.gradle.kts
```
import com.vk.id.health.metrics.buildspeed.buildSpeed
import com.vk.id.health.metrics.codecoverage.codeCoverage
import com.vk.id.health.metrics.gitlab.gitlab
import com.vk.id.health.metrics.storage.firestore
import java.util.Properties

// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    id("vkid.health.metrics") version "1.0.0-alpha03" apply true
}

healthMetrics {
    val localProperties by lazy {
        Properties().apply { load(rootProject.file("bot.properties").inputStream()) }
    }
    gitlab(
        host = { localProperties.getProperty("healthmetrics.gitlab.host") },
        token = { localProperties.getProperty("healthmetrics.gitlab.token") },
        projectId = { localProperties.getProperty("healthmetrics.gitlab.projectId") }
    )
    firestore(rootProject.file("build-logic/metrics/service-credentials.json"))
    codeCoverage {
        title = "Code coverage"
        targetProject = rootProject
    }
    buildSpeed {
        title = "Build speed of :assembleDebug"
        measuredTaskPaths = setOf(":assembleDebug")
        iterations = 3
        warmUps = 2
        cleanAfterEachBuild = true
    }
}
```
settings.gradle.kts
```
pluginManagement {
    repositories {
        maven(url = "https://artifactory-external.vkpartner.ru/artifactory/vkid-sdk-android/")
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "My Application"
include(":app")
```
3. Сделать gradle sync

### Ожидаемое поведение

Проект синканулся без ошибок

### Фактическое поведение

Проект не синкается с ошибкой описанной выше

### Используемые модули и их версии

vkid.health.metrics:1.0.0-alpha03

### Скриншоты

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/009300c9-882f-4fe2-beb3-0af03df3eafa">

### Смартфон или эмулятор

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/32198c87-39e3-4041-b87b-2727b574dd1e">

### Внутренний или внешний сервис

Нет

### Обновляли ли вы сдк

Нет

### Исправлена ли ошибка

Нет

### Где инициализиурете SDK

Нет сдк на проекте

### Версия клиента авторизации

Нет

### Дополнительные заметки

Есть предположение, что необходима дополнительная зависимость для buildSpeed. Также подозреваю что требуется kover для метрики с codeCoverage, но этот блок пока не подключал

**Comment by diklimchuk** [comment]
Здравствуйте, есть ли у вас таска :assembleDebug в корне проекта? Обычно есть только :app:assembleDebug. Если вам нужно померять результат `./gradlew assembleDebug` (без двоеточия), то нужно добавить в корневой build.gradle.kts примерно такой код:
```
tasks.register("assembleDebug") {
  subprojects.forEach { dependsOn(":${it.name}:assembleDebug") }
}
```

**Comment by Blighting** [comment]
Благодарю, теперь синкается. Нужно ли подобным образом регистрировать таску `clean`, которую будет использовать buildSpeed под капотом?

**Comment by diklimchuk** [comment]
Нет, под капотом вызывается `./gradlew clean` напрямую

**Comment by Blighting** [comment]
Ага, спасибо. А какой обычно путь до apkAnalyzer? Просто "apkanalyzer"?

**Comment by Blighting** [comment]
И еще вопрос про блок apkSize
```kotlin
    apkSize {
        title = "SDK size with all dependencies"
        targetProject = project
        targetBuildType = "debug"
        sourceBuildType = "debug"
        apkAnalyzerPath = { localProperties.getProperty("healthmetrics.apksize.apkanalyzerpath") }
    }
```
Выдает ошибку 
```
org.gradle.api.UnknownTaskException: Task with path ':cs:assembleDebug' not found in root project 'cs'.
	at org.gradle.api.internal.tasks.DefaultTaskContainer.getByPath(DefaultTaskContainer.java:492)
	at com.vk.id.health.metrics.apksize.VKIDApkSizeMetric.<init>(VKIDApkSizeMetric.kt:30)
	at com.vk.id.health.metrics.apksize.VKIDApkSizeMetric$Builder.build$metrics(VKIDApkSizeMetric.kt:106)
	at com.vk.id.health.metrics.apksize.VKIDApkSizeMetricKt.apkSize(VKIDApkSizeMetric.kt:17)
```
Хотя до этого таска была зарегана
```kotlin
tasks.register("assembleDebug") {
    subprojects.forEach { dependsOn(":${it.name}:assembleDebug") }
}
```
В чем может быть ошибка? buildType debug в проекте есть. 
Извиняюсь, что так много вопросов задаю. Надеюсь они помогут выявить все подводные камни при настройке плагина, чтобы потом можно было добавить информацию в статью на хабре/пример подключения

**Comment by diklimchuk** [comment]
> А какой обычно путь до apkAnalyzer? Просто "apkanalyzer"?
Если локально, то это путь до него в cmdline-tools, у меня на маке /Users/User/Library/Android/sdk/cmdline-tools/latest/bin/apkanalyzer. На CI нужно уставить cmdline-tools в докер образ и указать путь по аналогии

**Comment by diklimchuk** [comment]
> Хотя до этого таска была зарегана

Тут немного другая таска, та, что зарегистрирована в корне, а в apkSize блоке видимо project(":cs"). В нем должна быть таска assembleDebug

**Comment by Blighting** [comment]
> > Хотя до этого таска была зарегана
> 
> Тут немного другая таска, та, что зарегистрирована в корне, а в apkSize блоке видимо project(":cs"). В нем должна быть таска assembleDebug

Неочевидно пока как такое исправить, мб какую-то доку нужно прочитать?

**Comment by Blighting** [comment]
> Все в порядке, я расскажу все, что нужно. Статья с гайдом по настройке планируется, когда метрики переедут в отдельный реп, а это может быть не скоро

А когда примерно появится такая статья? Пока что выглядит так, что проще дождаться гайда по настройке

**Comment by diklimchuk** [comment]
> Неочевидно пока как такое исправить, мб какую-то доку нужно прочитать?

Доки нет, если размер апк можно посчитать только для android application проекта. 
А если этот плагин подключен, то таска assembleDebug уже есть

**Comment by Blighting** [comment]
Добрый день, вроде настроил плагин, но на CI не запускается
На данный момент в build.gradle.kts выглядит вот так, но service cred'ы для firestore пока кривые(в первой итерации хочет увидеть результат просто на CI)
```kotlin
healthMetrics {
    val localProperties by lazy {
        Properties().apply { load(rootProject.file("build-logic/bot.properties").inputStream()) }
    }
    gitlab(
        host = { localProperties.getProperty("healthmetrics.gitlab.host") },
        token = { localProperties.getProperty("healthmetrics.gitlab.token") },
        projectId = { localProperties.getProperty("healthmetrics.gitlab.projectId") },
    )
    firestore(rootProject.file("build-logic/metrics/service-credentials.json"))
    codeCoverage {
        title = "Code coverage"
        targetProject = rootProject
    }
    buildSpeed {
        title = "Build speed of :assembleDebug"
        measuredTaskPaths = setOf(":assembleDebug")
        iterations = 3
        warmUps = 2
        cleanAfterEachBuild = true
    }
}
```
Проперти выглядят вот так
```
healthmetrics.gitlab.token = "some token"
healthmetrics.gitlab.host = "https://gitlab.some.host/"
healthmetrics.gitlab.projectId = "99999"
```
Возможно ли как-то отдебажить работу плагина, чтобы посмотреть потенциальные ошибки/логи?

**Comment by diklimchuk** [comment]
Приветствую!
Потенциально ошибка в неверных service-credentials, без корректного файла плагин не будет работать. Кроме этого немного смущает путь "build-logic/metrics/service-credentials.json", не уверен, что у вас есть папка metrics. Если пришлете ошибку смогу сказать точнее в чем дело. 

Продебагать сейчас можно только скопировав к себе исходники и подключив плагин из них, как в этом репозитории. После этого нужно:
- Запустить таску gradle :publishHealthMetrics --stacktrace -PhealthMetrics.common.mergeRequestId=655 из студии (через окошко со слоником в правой колонке)
- Остановить
- Поставить брейкпойнт в исходниках
- Нажать на кнопку дебага

**Comment by Blighting** [comment]
А какие конкретно креды ожидает service-credentials файлик для Firestore? Саму БД в Firestore завел, но что конкретно отдать плагину неочевидно

**Comment by diklimchuk** [comment]
Там все просто. Что бы его получить, нужно в Project Settgins/Service Account нажать на "Generate new private key" и сохранить файлик в проект

**Comment by Blighting** [comment]
Мб не хватает каких-то зависимостей типо gson'а? Или плагин их сам должен подтягивать

**Comment by diklimchuk** [comment]
Должно работать автоматически. Так не могу сказать, какая у вас ошибка?

**Comment by Blighting** [comment]
Добрый день, болел, поэтому не настраивал плагин прошлую неделю. На данный момент на этапе отправки в Firestore 
`[com.google.api.gax.rpc.FailedPrecondition Exception: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: The Cloud Firestore API is not available for Firestore in Datastore Mode database](https://www.google.com/search?sca_esv=91c658cd3c6ca43c&q=:+com.google.api.gax.rpc.FailedPrecondition+Exception:+io.grpc.StatusRuntimeException:+FAILED_PRECONDITION:+The+Cloud+Firestore+API+is+not+available+for+Firestore+in+Datastore+Mode+database&spell=1&sa=X&ved=2ahUKEwi116rl37WJAxU6HxAIHVTzM5sQBSgAegQINhAB)`
Обычно такая проблема связана с тем, что БД не в Native mode, но у меня в Native mode стоит. Мб нужны еще какие-то доп настройки?

**Comment by diklimchuk** [comment]
> Добрый день, болел, поэтому не настраивал плагин прошлую неделю. На данный момент на этапе отправки в Firestore `[com.google.api.gax.rpc.FailedPrecondition Exception: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: The Cloud Firestore API is not available for Firestore in Datastore Mode database](https://www.google.com/search?sca_esv=91c658cd3c6ca43c&q=:+com.google.api.gax.rpc.FailedPrecondition+Exception:+io.grpc.StatusRuntimeException:+FAILED_PRECONDITION:+The+Cloud+Firestore+API+is+not+available+for+Firestore+in+Datastore+Mode+database&spell=1&sa=X&ved=2ahUKEwi116rl37WJAxU6HxAIHVTzM5sQBSgAegQINhAB)` Обычно такая проблема связана с тем, что БД не в Native mode, но у меня в Native mode стоит. Мб нужны еще какие-то доп настройки?

Приветствую, вы пробовали вот этот ответ со stackoverflow? https://stackoverflow.com/a/70495872/5471822

**Comment by Blighting** [comment]
Добрый день, да пробовал

**Comment by Blighting** [comment]
Добрый день, добрались руки до плагина, получилось настроить с buildTime. Подскажите пожалуйста как настроить apkSize. Например неочевидно что долго лежать по пути healthmetrics.apksize.apkanalyzerpath. Можно ли как-то брать уже готовый билд из папки build? Чтобы 2 раз не собирать(на CI до на пайплайне джоба собирает до этого уже собирает нужную сборку)

**Comment by diklimchuk** [comment]
@Blighting Приветствую. В healthmetrics.apksize.apkanalyzerpath должен находиться путь до [apkanalyzer](https://developer.android.com/tools/apkanalyzer). Локально должно быть примерно так: /Users/USER_NAME/Library/Android/sdk/cmdline-tools/latest/bin/apkanalyzer. На Ci нужно установить [command-line tools](https://developer.android.com/tools) и прописать путь до них
